### PR TITLE
[WIP] 13.3 bounding boxes

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-826/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-826/

**Comment by npudqsz** [comment]
Hello,
Why would you prefer to add new lines ? Thanks !

**Comment by goldmermaid** [comment]
> Hello,
> Why would you prefer to add new lines ? Thanks !

Great question! In a short word, this way will improve the adaptability when different people are collaborating. Suppose one paragraph has sentence a,b,c, etc. Now developer A comes in and edits sentence a, while at the same time developer C edits sentence c. Git won't figure out how to incorporate the changes together, and it would be difficult for the reviewers to handle this scenario. Another reason is that we will add more "slides" symbols into each section in the future. A line with shorter sentence would help us minimize the modified content.

**Comment by npudqsz** [comment]
> 
> 
> > Hello,
> > Why would you prefer to add new lines ? Thanks !
> 
> Great question! In a short word, this way will improve the adaptability when different people are collaborating. Suppose one paragraph has sentence a,b,c, etc. Now developer A comes in and edits sentence a, while at the same time developer C edits sentence c. Git won't figure out how to incorporate the changes together, and it would be difficult for the reviewers to handle this scenario. Another reason is that we will add more "slides" symbols into each section in the future. A line with shorter sentence would help us minimize the modified content.

I got it ! I just found that a linebreak won't tear apart a paragraph but a new blank line will. This is a good idea and practice ! So basically we can do the same thing to all the other 'xx.md' sections ?
(just another question : what do you mean by 'slides' symbols ? what does it look like and work for? In d2l website or .ipynb file ?)
Thanks for your response !

**Comment by goldmermaid** [comment]
>  what do you mean by 'slides' symbols ? what does it look like and work for? In d2l website or .ipynb file ?

Yea, great question. We are using those special [symbols](https://book.d2l.ai/user/slides.html) to create slides for Mu's MOOC course.

> So basically we can do the same thing to all the other 'xx.md' sections ?

You don't need to follow that. (It is my "mark" to make sure I have reviewed that file.)

**Comment by npudqsz** [comment]
Cool ! I understand now. Bon courage \o/

**Comment by goldmermaid** [comment]
Reviewed http://preview.d2l.ai/d2l-zh/PR-826/chapter_computer-vision/bounding-box.html:
- no `numref` or `cite` issue
- forum links updated

**Pull request merged**
