### PR TITLE
[Paddle]Add chapter_natural-language-processing-pretraining

### PR DESCRIPTION
**Pull request by tngt**

### CODE REVIEW

**Comment by cheungdaven** [comment]
subword-embedding is missing.

**Comment by tngt** [comment]
> subword-embedding is missing.

In subword-embedding，the implementation is the same, we use #@tab all.

**Comment by tngt** [comment]
> subword-embedding is missing.

but we found that in http://preview.d2l.ai/d2l-zh/PR-1177/, The tab PADDLE is missing here， we dont know why！
图片

**Comment by cheungdaven** [comment]
> > subword-embedding is missing.
> 
> but we found that in http://preview.d2l.ai/d2l-zh/PR-1177/, The tab PADDLE is missing here， we dont know why！ 图片

You can add a space somewhere in the subword-embedding.md, so it will be triggered for compilation.

**Comment by tngt** [comment]
> > > subword-embedding is missing.
> > 
> > 
> > but we found that in http://preview.d2l.ai/d2l-zh/PR-1177/, The tab PADDLE is missing here， we dont know why！ 图片
> 
> You can add a space somewhere in the subword-embedding.md, so it will be triggered for compilation.

Thanks for your suggestion, it works now. Could you review it again? Thanks！！！

**Review by cheungdaven — CHANGES_REQUESTED** [review]

**Comment by cheungdaven** [comment]
I actually saw the following warning for a few times. It is possible for paddlepaddle to fix that?

> /home/d2l-worker/miniconda3/envs/d2l-zh-paddle-1/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: np.object is a deprecated alias for the builtin object. To silence this warning, use object by itself. Doing this will not modify any behavior and is safe.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   if data.dtype == np.object:

**Pull request merged**
