### PR TITLE
[Don't merge]Just Build PDF[PyTorch]

### PR DESCRIPTION
**Pull request by StevenJokess**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-715/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-715/

**Comment by StevenJokess** [comment]
`d2lbook build pdf --tab PyTorch` is not working now.

**Comment by mli** [comment]
Job d2l-zh/PR-715/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-715/

**Comment by StevenJokess** [comment]
Still MXnet version...
http://preview.d2l.ai/d2l-zh/PR-715/d2l-zh.pdf

**Comment by GreenTeaHua** [comment]
any master have the pytorch version?

**Pull request closed without merging**
