### PR TITLE
remove space

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by goldmermaid** [comment]
TODO: View preview before merging

**Comment by mli** [comment]
Job d2l-zh/PR-898/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-898/

**Comment by mli** [comment]
Job d2l-zh/PR-898/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-898/

**Comment by mli** [comment]
Job d2l-zh/PR-898/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-898/

**Comment by mli** [comment]
Job d2l-zh/PR-898/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-898/

**Pull request merged**
