### PR TITLE
Pre-release for v2.0.0-beta0

### PR DESCRIPTION
**Pull request by astonzhang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-1026/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1026/

**Comment by mli** [comment]
Job d2l-zh/PR-1026/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1026/

**Comment by mli** [comment]
Job d2l-zh/PR-1026/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1026/

**Comment by mli** [comment]
Job d2l-zh/PR-1026/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1026/

**Comment by astonzhang** [comment]
cc @xiaotinghe, @goldmermaid, and @mli 
Thanks for the hard work!

**Pull request merged**
