### PR TITLE
Chapter computational performance/parameterserver

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-848/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by mli** [comment]
Job d2l-zh/PR-848/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Review by goldmermaid — APPROVED** [review]
Wonderful! Thanks @zhuyuanxiang

**Comment by zhuyuanxiang** [comment]
> Wonderful! Thanks @zhuyuanxiang

Thks for your affirmation.

**Comment by mli** [comment]
Job d2l-zh/PR-848/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by mli** [comment]
Job d2l-zh/PR-848/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by goldmermaid** [comment]
> > Wonderful! Thanks @zhuyuanxiang
> 
> Thks for your affirmation.

Quick question. Is that PR still working in process (WIP)? If not, could you please remove the [WIP] from the tile? Thanks!

**Comment by zhuyuanxiang** [comment]
> > > Wonderful! Thanks @zhuyuanxiang
> > 
> > 
> > Thks for your affirmation.
> 
> Quick question. Is that PR still working in process (WIP)? If not, could you please remove the [WIP] from the tile? Thanks!

I plan to review it again, and then I will remove WIP.

**Comment by zhuyuanxiang** [comment]
With the deepening of study, I had an advanced understand about the article, and I try to easy to understand the translation for the reader.
I hoped to along with the standardization management by the terms.
Now, It's OK.
Thks for your help.

**Comment by mli** [comment]
Job d2l-zh/PR-848/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by goldmermaid** [comment]
> With the deepening of study, I had an advanced understand about the article, and I try to easy to understand the translation for the reader.
> I hoped to along with the standardization management by the terms.
> Now, It's OK.
> Thks for your help.

I can tell the improvement you made! Thanks for the exceptional work @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-848/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by mli** [comment]
Job d2l-zh/PR-848/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-848/

**Comment by zhuyuanxiang** [comment]
> I can tell the improvement you made!

I’ve learned so much from you, and I appreciate the encouragement that you offered me when I first struggled to meet my quota.

**Pull request merged**
