### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by yl7466**
Initialize b2 to 0 to align with mxnet & pytorch code block.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-1028/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1028/

**Comment by mli** [comment]
Job d2l-zh/PR-1028/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1028/

**Comment by mli** [comment]
Job d2l-zh/PR-1028/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1028/

**Review by goldmermaid — APPROVED** [review]
Thanks! @yl7466

**Pull request merged**
