### PR TITLE
Chapter recurrent modern/bi rnn

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-859/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-859/

**Comment by mli** [comment]
Job d2l-zh/PR-859/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-859/

**Comment by mli** [comment]
Job d2l-zh/PR-859/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-859/

**Comment by mli** [comment]
Job d2l-zh/PR-859/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-859/

**Comment by mli** [comment]
Job d2l-zh/PR-859/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-859/

**Review by goldmermaid — APPROVED** [review]
Great work @zhuyuanxiang !

**Pull request merged**
