### PR TITLE
fix 4.4.1.2. Model Complexity translation issues

### PR DESCRIPTION
**Pull request by WilliamWuLH**
translation issues in 4.4.1.2. Model Complexity

根据自由度的定义和本书英文版此处的说明 [“ When the number of tunable parameters, sometimes called the *degrees of freedom* ”](https://d2l.ai/chapter_multilayer-perceptrons/underfit-overfit.html#model-complexity)，我认为 [此处](https://zh-v2.d2l.ai/chapter_multilayer-perceptrons/underfit-overfit.html#id4) 翻译为 “当可调整参数的数量（有时称为自由度）很大时” 更为合适并且更好理解。 Thanks!

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-706/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-706/

**Comment by WilliamWuLH** [comment]
fix typo in chapter_multilayer-perceptrons/environment.md

**Comment by mli** [comment]
Job d2l-zh/PR-706/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-706/

**Review by goldmermaid — APPROVED** [review]
Thanks for you contribution @WilliamWuLH !

**Pull request merged**
