### PR TITLE
Installation Updates

### PR DESCRIPTION
**Pull request by goldmermaid**
Align with https://github.com/d2l-ai/d2l-en/blame/master/chapter_installation/index.md

- [x] Need to verify the preview html between d2l-en and d2l-zh

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-974/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-974/

**Comment by mli** [comment]
Job d2l-zh/PR-974/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-974/

**Comment by mli** [comment]
Job d2l-zh/PR-974/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-974/

**Comment by goldmermaid** [comment]
Hey @astonzhang , would you like to take a look before I merge this PR? You can compare between [d2l-en preview](http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_installation/index.html) and this PR's preview.

**Pull request merged**
