### PR TITLE
润色翻译

### PR DESCRIPTION
**Pull request by chjxz**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-785/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by chjxz** [comment]
some fix and translation

**Comment by mli** [comment]
Job d2l-zh/PR-785/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/13 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/14 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/15 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/16 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/17 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Comment by mli** [comment]
Job d2l-zh/PR-785/18 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-785/

**Pull request merged**
