### PR TITLE
chapter_recurrent-modern/deep-rnn

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-858/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-858/

**Comment by mli** [comment]
Job d2l-zh/PR-858/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-858/

**Comment by mli** [comment]
Job d2l-zh/PR-858/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-858/

**Comment by mli** [comment]
Job d2l-zh/PR-858/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-858/

**Comment by goldmermaid** [comment]
Great work @zhuyuanxiang !

**Pull request merged**
