### PR TITLE
modified:   chapter_attention-mechanisms/attention-scoring-functions.md

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-644/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by mli** [comment]
Job d2l-zh/PR-644/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by mli** [comment]
Job d2l-zh/PR-644/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by mli** [comment]
Job d2l-zh/PR-644/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by mli** [comment]
Job d2l-zh/PR-644/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by mli** [comment]
Job d2l-zh/PR-644/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-644/

**Comment by astonzhang** [comment]
Closing due to conflict and branch rebase. You may re-open it later on the rebased branch. Thanks.

**Pull request closed without merging**
