### PR TITLE
Chapter computational performance/parameterserver

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-844/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-844/

**Comment by mli** [comment]
Job d2l-zh/PR-844/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-844/

**Review by goldmermaid — APPROVED** [review]
Great work @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-844/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-844/

**Pull request merged**
