### PR TITLE
Troubleshoot the data synchronization failure

### PR DESCRIPTION
**Pull request by A-FM**
@AnirudhDagar 

The previous pull request was too messy, so I deleted it and re-forked it

Thanks for your advice and forgive my poor python knowledge.

Do you think it's ok to change the source code to this?

---

The problem with the code is that it does not synchronize data to all gpus, as shown in the following code.

```python
%matplotlib inline
from d2l import torch as d2l
import torch
from torch import nn
from torch.nn import functional as F
def allreduce(data):
    for i in range(1, len(data)):
        data[0][:] += data[i].to(data[0].device)
    for i in range(1, len(data)):
        data[i] = data[0].to(data[i].device)
        
test_rd = [torch.ones((1, 2), device=d2l.try_gpu(0)),torch.ones((1, 2), device=d2l.try_gpu(1))*2]


data = [test_rd[i] for i in range(2)]

print('before allreduce:\n', test_rd[0], '\n', test_rd[1])
allreduce(data)
print('after allreduce:\n', test_rd[0], '\n', test_rd[1])
print('data:\n',data[0],'\n',data[1])
```

### CODE REVIEW

**Comment by A-FM** [comment]
In the original code, only the data on the first GPU was changed, the others were not.

**Comment by A-FM** [comment]
Since this is my first pull request, I have no experience. I'm sorry. I will be more careful in future revisions.

**Comment by A-FM** [comment]
@AnirudhDagar I didn't know much about Python in-place operation before, but I learned a lot through this pull request. Thank you for your advice.

**Comment by mli** [comment]
Job d2l-zh/PR-1021/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1021/

**Review by AnirudhDagar — APPROVED** [review]
Thanks @A-FM! LGTM now.
This should fix the issue.

> The previous pull request was too messy, so I deleted it and re-forked it. Since this is my first pull request, I have no experience. I'm sorry. I will be more careful in future revisions.

No worries, we all have to start somewhere. Every developer has gone through this phase. :)

> I didn't know much about Python in-place operation before, but I learned a lot through this pull request. Thank you for your advice.

Glad that I could help, feel free to ask your questions when in doubt.

@goldmermaid let's get this in.

Edit 1: Linking the previous PR #955 for reference.

**Review by AnirudhDagar — APPROVED** [review]

**Pull request merged**
