### PR TITLE
Chapter recurrent modern/beam search

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-870/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Comment by mli** [comment]
Job d2l-zh/PR-870/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Comment by mli** [comment]
Job d2l-zh/PR-870/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Comment by mli** [comment]
Job d2l-zh/PR-870/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Comment by mli** [comment]
Job d2l-zh/PR-870/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Review by goldmermaid — APPROVED** [review]
Great work @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-870/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-870/

**Pull request merged**
