### PR TITLE
chapter_recurrent-modern/gru

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-856/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-856/

**Comment by mli** [comment]
Job d2l-zh/PR-856/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-856/

**Review by goldmermaid — APPROVED** [review]
Fabulous work! Thanks @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-856/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-856/

**Pull request merged**
