### PR TITLE
[Terminology] 标记 / 令牌 -> 词元

### PR DESCRIPTION
**Pull request by goldmermaid**
- [x] 标记 -> 词元

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-916/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-916/

**Comment by mli** [comment]
Job d2l-zh/PR-916/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-916/

**Comment by mli** [comment]
Job d2l-zh/PR-916/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-916/

**Comment by goldmermaid** [comment]
Finished TODO for #pr897

**Comment by mli** [comment]
Job d2l-zh/PR-916/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-916/

**Pull request merged**
