### PR TITLE
chapter_convolutional-neural-networks/index

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-899/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-899/

**Comment by mli** [comment]
Job d2l-zh/PR-899/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-899/

**Review by goldmermaid — APPROVED** [review]
Thanks for your amazing work! @zhuyuanxiang

**Comment by mli** [comment]
Job d2l-zh/PR-899/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-899/

**Pull request merged**
