### PR TITLE
translation of 'reduction' in linear-algebra

### PR DESCRIPTION
**Pull request by npudqsz**
Using 降维 instead of 汇总 as the translation of 'reduction' may be easier to understand for readers, as I proposed in the discussion of the corresponding chapter.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-816/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-816/

**Review by goldmermaid — APPROVED** [review]
Thanks @npudqsz !

**Comment by mli** [comment]
Job d2l-zh/PR-816/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-816/

**Comment by mli** [comment]
Job d2l-zh/PR-816/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-816/

**Pull request merged**
