### PR TITLE
new file:   chapter_computational-performance/index_origin.md

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-646/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by mli** [comment]
Job d2l-zh/PR-646/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by mli** [comment]
Job d2l-zh/PR-646/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by xinetzone** [comment]
@mli can it merge?

**Comment by mli** [comment]
Job d2l-zh/PR-646/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by mli** [comment]
Job d2l-zh/PR-646/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by mli** [comment]
Job d2l-zh/PR-646/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by mli** [comment]
Job d2l-zh/PR-646/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-646/

**Comment by astonzhang** [comment]
Please do not modify xx_origin files

**Pull request closed without merging**
