### PR TITLE
Chapter 1-7 Discussion Links

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-624/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-624/

**Comment by astonzhang** [comment]
Since v1 uses these titles, let's keep this original titles unless the press has a strong opinion about it.

**Comment by mli** [comment]
Job d2l-zh/PR-624/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-624/

**Comment by mli** [comment]
Job d2l-zh/PR-624/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-624/

**Comment by mli** [comment]
Job d2l-zh/PR-624/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-624/

**Pull request merged**
