### PR TITLE
fix errors in chapter_attention-mechanisms/nadaraya-waston.md

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-739/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-739/

**Comment by goldmermaid** [comment]
@xiaotinghe could you take a look? Thanks!

**Comment by mli** [comment]
Job d2l-zh/PR-739/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-739/

**Comment by mli** [comment]
Job d2l-zh/PR-739/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-739/

**Pull request merged**
