### PR TITLE
modified:   chapter_attention-mechanisms/nadaraya-waston.md

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-643/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by mli** [comment]
Job d2l-zh/PR-643/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by mli** [comment]
Job d2l-zh/PR-643/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by mli** [comment]
Job d2l-zh/PR-643/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by mli** [comment]
Job d2l-zh/PR-643/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by mli** [comment]
Job d2l-zh/PR-643/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-643/

**Comment by astonzhang** [comment]
Closing due to conflict and branch rebase. You may re-open it later on the rebased branch. Thanks.

**Pull request closed without merging**
