### PR TITLE
[WIP] Improve performance on the Kaggle small-scale CIFAR-10 and ImageNet Dog dataset

### PR DESCRIPTION
**Pull request by goldmermaid**
Fixes for [issue](https://github.com/d2l-ai/d2l-en/issues/1775).

Refer:
MXNet:
https://github.com/d2l-ai/d2l-en/commit/8b325e369d3723fd3d700a2c5356afcb135ff818
https://github.com/d2l-ai/d2l-en/commit/2827fe50b227052bbc5b5ebc8948baebac955da1
https://github.com/d2l-ai/d2l-en/commit/aa2a9a3e041b684ae434a9af470e8aa92aa26fb8
https://github.com/d2l-ai/d2l-en/commit/0da9c0646ddc6e6c8c9512296414ccbf4bdb9857

PyTorch:
https://github.com/d2l-ai/d2l-en/pull/1783/files
https://github.com/d2l-ai/d2l-en/pull/1784/files

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-855/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-855/

**Comment by goldmermaid** [comment]
Don't merge, need to confirm the PyTorch fixes.

**Comment by mli** [comment]
Job d2l-zh/PR-855/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-855/

**Comment by mli** [comment]
Job d2l-zh/PR-855/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-855/

**Comment by mli** [comment]
Job d2l-zh/PR-855/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-855/

**Comment by goldmermaid** [comment]
Migration done! Need to review the preview files before merging.

**Comment by mli** [comment]
Job d2l-zh/PR-855/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-855/

**Comment by goldmermaid** [comment]
Preview version performance check done for both files!

**Pull request merged**
