### PR TITLE
Chapter computational performance/hybridize

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-828/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-828/

**Comment by mli** [comment]
Job d2l-zh/PR-828/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-828/

**Comment by mli** [comment]
Job d2l-zh/PR-828/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-828/

**Review by goldmermaid — APPROVED** [review]
Fabulous work @zhuyuanxiang ! (I made a little bit adjustments. Let me know if you have any questions on those.)

**Comment by zhuyuanxiang** [comment]
> Fabulous work @zhuyuanxiang ! (I made a little bit adjustments. Let me know if you have any questions on those.)

I think that the bold font is better than the italic font in Chinese Character for emphasizing sth, so I changed it and I hope to exchange idea with others.

**Pull request merged**
