### PR TITLE
Chapter recurrent neural networks/bptt

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-896/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-896/

**Comment by mli** [comment]
Job d2l-zh/PR-896/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-896/

**Comment by mli** [comment]
Job d2l-zh/PR-896/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-896/

**Comment by mli** [comment]
Job d2l-zh/PR-896/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-896/

**Review by goldmermaid — APPROVED** [review]
Fabulous! @zhuyuanxiang

**Pull request merged**
