### PR TITLE
resnet代码有问题，第一个模块也用到了1*1 conv，只是没有downsampling

### PR DESCRIPTION
**Pull request by chenying99**
resnet代码有问题，第一个模块也用到了1*1 conv，只是没有downsampling

### CODE REVIEW

**Comment by goldmermaid** [comment]
Thanks for raising the issue @chenying99 !  Could you resolving the above conflicts?

Also, could you also post a PR at https://github.com/d2l-ai/d2l-en/pulls for consistency?

**Comment by chenying99** [comment]
> consistency



> Thanks for raising the issue @chenying99 ! Could you resolving the above conflicts?
> 
> Also, could you also post a PR at https://github.com/d2l-ai/d2l-en/pulls for consistency?

I have  also post a PR at https://github.com/d2l-ai/d2l-en/pulls

**Comment by chenying99** [comment]
> consistency



> Thanks for raising the issue @chenying99 ! Could you resolving the above conflicts?
> 
> Also, could you also post a PR at https://github.com/d2l-ai/d2l-en/pulls for consistency?

I have  also post a PR at https://github.com/d2l-ai/d2l-en/pulls

**Comment by chenying99** [comment]
> Thanks for raising the issue @chenying99 ! Could you resolving the above conflicts?
> 
> Also, could you also post a PR at https://github.com/d2l-ai/d2l-en/pulls for consistency?

Check the results at http://preview.d2l.ai/d2l-en/PR-1839/chapter_convolutional-modern/resnet.html

**Pull request closed without merging**
