### PR TITLE
'1x1 kernel' display fix

### PR DESCRIPTION
**Pull request by npudqsz**
Try to fix the display error in the begining of 6.4.3 section - 1x1 kernel.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-881/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-881/

**Comment by npudqsz** [comment]
Error not fixed.. Could you have a look, please ?
Thanks.

**Comment by mli** [comment]
Job d2l-zh/PR-881/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-881/

**Comment by mli** [comment]
Job d2l-zh/PR-881/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-881/

**Comment by goldmermaid** [comment]
Hey @npudqsz , could you take a look the fixes http://preview.d2l.ai/d2l-zh/PR-881/chapter_convolutional-neural-networks/channels.html and let me know if you are okay with that?

**Comment by npudqsz** [comment]
> 
> 
> Hey @npudqsz , could you take a look the fixes http://preview.d2l.ai/d2l-zh/PR-881/chapter_convolutional-neural-networks/channels.html and let me know if you are okay with that?

Yes! Error fixed! 
So what is the reason ?
You can merge it. Thanks!

**Comment by goldmermaid** [comment]
> > Hey @npudqsz , could you take a look the fixes http://preview.d2l.ai/d2l-zh/PR-881/chapter_convolutional-neural-networks/channels.html and let me know if you are okay with that?
> 
> Yes! Error fixed!
> So what is the reason ?
> You can merge it. Thanks!

I suspect the last space in "$1 \times 1 $" caused the bug.

**Pull request merged**
