### PR TITLE
Intro Done

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-623/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by astonzhang** [comment]
For passing CI, can you rebase it to the HEAD of v2 branch?

**Comment by mli** [comment]
Job d2l-zh/PR-623/21 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/22 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/23 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/24 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/25 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/26 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by goldmermaid** [comment]
All tests are passed! :)

**Comment by astonzhang** [comment]
For passing CI, can you rebase it to the HEAD of v2 branch?
@xiaotinghe , would you like to review this PR? Thanks!

**Comment by mli** [comment]
Job d2l-zh/PR-623/29 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/30 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/31 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/33 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/36 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/40 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/41 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/43 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by astonzhang** [comment]
@xiaotinghe  Can you take a look before merging this?

**Comment by mli** [comment]
Job d2l-zh/PR-623/44 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by mli** [comment]
Job d2l-zh/PR-623/45 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-623/

**Comment by astonzhang** [comment]
@xiaotinghe I'm merging this first before branch rebase. You may wish to take a look at these changes later.

**Pull request merged**
