### PR TITLE
[WIP] 13.8 RCNN

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-851/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-851/

**Comment by mli** [comment]
Job d2l-zh/PR-851/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-851/

**Comment by mli** [comment]
Job d2l-zh/PR-851/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-851/

**Comment by goldmermaid** [comment]
- Forum links done;
- `numref` checked;
- `cite` added;

**Comment by mli** [comment]
Job d2l-zh/PR-851/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-851/

**Pull request merged**
