### PR TITLE
[slides] CNN

### PR DESCRIPTION
**Pull request by goldmermaid**
Check no 404 before merge. https://github.com/d2l-ai/d2l-zh-pytorch-slides

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-753/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/13 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by goldmermaid** [comment]
https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/pooling.ipynb

https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/conv-layer.ipynb

Done

**Comment by goldmermaid** [comment]
Lenet Done!
https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/lenet.ipynb#/

**Comment by mli** [comment]
Job d2l-zh/PR-753/14 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by mli** [comment]
Job d2l-zh/PR-753/15 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by goldmermaid** [comment]
Channels 404 Fixed

https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/channels.ipynb#/

**Comment by mli** [comment]
Job d2l-zh/PR-753/16 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-753/

**Comment by goldmermaid** [comment]
Padding and stride done!
https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/padding-and-strides.ipynb

**Comment by astonzhang** [comment]
> Padding and stride 404 fixed!
> https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/padding-and-strides.ipynb

Sounds good. Did you figure out the root cause?

**Comment by goldmermaid** [comment]
> > Padding and stride 404 fixed!
> > https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_convolutional-neural-networks/padding-and-strides.ipynb
> 
> Sounds good. Did you figure out the root cause?

It is a bit tricky. Until now, I noticed that `*`, `$` and space may cause 404 if there are inside `[**` and `**]`.

**Pull request merged**
