### PR TITLE
Chapter recurrent modern/lstm

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-857/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Comment by mli** [comment]
Job d2l-zh/PR-857/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Review by goldmermaid — APPROVED** [review]
Fabulous work! Thanks @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-857/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Comment by mli** [comment]
Job d2l-zh/PR-857/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Comment by mli** [comment]
Job d2l-zh/PR-857/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Comment by mli** [comment]
Job d2l-zh/PR-857/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-857/

**Comment by goldmermaid** [comment]
`cite` and `numref`fixed: should either add a space in the front or changing from "（" to "("

**Pull request merged**
