### PR TITLE
[polish] chapter 4 polishing

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-1002/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1002/

**Comment by mli** [comment]
Job d2l-zh/PR-1002/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1002/

**Comment by mli** [comment]
Job d2l-zh/PR-1002/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1002/

**Comment by mli** [comment]
Job d2l-zh/PR-1002/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1002/

**Comment by mli** [comment]
Job d2l-zh/PR-1002/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-1002/

**Comment by goldmermaid** [comment]
- [ ] preview checked

**Pull request merged**
