### PR TITLE
[PaddlePaddle] Merge master into Paddle branch

### PR DESCRIPTION
**Pull request by w5688414**

### CODE REVIEW

**Comment by tngt** [comment]
> Besides, do we still need #1122 and #1116?

We don't need these two PR，Thanks！

**Comment by w5688414** [comment]
Hi, Thanks. the recent changes on master branch are incorporated into this pr, can you review this pr again? @astonzhang @cheungdaven

**Comment by astonzhang** [comment]
Quick issue:
https://github.com/d2l-ai/d2l-zh/blob/paddle/static/build.yml looks outdated, can you also sync the env from the master branch?

@cheungdaven PTAL

**Comment by w5688414** [comment]
> Quick issue: https://github.com/d2l-ai/d2l-zh/blob/paddle/static/build.yml looks outdated, can you also sync the env from the master branch?
> 
> @cheungdaven PTAL

it seems that  when I add     `- d2l==0.17.5 ` to build.yml，the ci failed and there are conflicts here

**Comment by astonzhang** [comment]
> > Quick issue: https://github.com/d2l-ai/d2l-zh/blob/paddle/static/build.yml looks outdated, can you also sync the env from the master branch?
> > @cheungdaven PTAL
> 
> it seems that when I add `- d2l==0.17.5 ` to build.yml，the ci failed and there are conflicts here

d2l==0.17.5 does not contain paddle code while `..` means installing from source (containing d2l/paddle.py) on the paddle branch. Please copy d2l/mxnet.py, d2l/torch.py, and d2l/tensorflow.py from the 0.17.5 release source: https://github.com/d2l-ai/d2l-en/tree/v0.17.5/d2l  to paddle branch and keep `..` in build.yml. In this way, installing d2l from your source will include all the d2l==0.17.5 code, together with the `d2l/paddle.py`. We may consider uploading d2l==0.17.6 containing paddle implementation later.

**Comment by cheungdaven** [comment]
@d2l-bot please rebuild

**Comment by w5688414** [comment]
image

I tried to upgrade pandas version, it seems there are conflicts here

**Comment by w5688414** [comment]
@d2l-bot please rebuild

**Comment by w5688414** [comment]
can you assist me to hidden the extra logs, it seems that using warningfilter does not worsk. @cheungdaven 
image

**Comment by cheungdaven** [comment]
> can you assist me to hidden the extra logs, it seems that using warningfilter does not worsk. @cheungdaven
> 
> image

@w5688414  Please follow this commit, it should be able to disable the logs. 
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-modern/gru.html

solution: put the line "warnings.filterwarnings("ignore", category=DeprecationWarning)" right before the line "from d2l import paddle as d2l"

**Comment by w5688414** [comment]
@d2l-bot please rebuild

**Comment by w5688414** [comment]
@d2l-bot please rebuild

**Comment by w5688414** [comment]
@d2l-bot please rebuild

**Comment by w5688414** [comment]
the too much logging task has been solved, can you review this pr again? @astonzhang , @cheungdaven

**Comment by cheungdaven** [comment]
The following log is still there, could you try to solve that? @w5688414 


 /home/d2l-worker/miniconda3/envs/d2l-zh-paddle-0/lib/python3.9/site-packages/paddle/fluid/framework.py:516: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(

**Comment by w5688414** [comment]
> The following log is still there, could you try to solve that? @w5688414
> 
> /home/d2l-worker/miniconda3/envs/d2l-zh-paddle-0/lib/python3.9/site-packages/paddle/fluid/framework.py:516: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default. warnings.warn(

the warning log has been ignored by warnings api, can you review it again? @cheungdaven  @astonzhang

**Comment by cheungdaven** [comment]
After a random check, I found a lot of logs are still there. The following is not a thorough list (I believe there are more files with logs). Could you have a thorough check? @w5688414 
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_computational-performance/hybridize.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_convolutional-modern/resnet.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_convolutional-modern/densenet.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/sequence.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/text-preprocessing.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/language-models-and-dataset.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/rnn.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-modern/machine-translation-and-dataset.html
http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-modern/encoder-decoder.html

**Comment by w5688414** [comment]
> After a random check, I found a lot of logs are still there. The following is not a thorough list (I believe there are more files with logs). Could you have a thorough check? @w5688414 http://preview.d2l.ai/d2l-zh/PR-1186/chapter_computational-performance/hybridize.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_convolutional-modern/resnet.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_convolutional-modern/densenet.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/sequence.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/text-preprocessing.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/language-models-and-dataset.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-neural-networks/rnn.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-modern/machine-translation-and-dataset.html http://preview.d2l.ai/d2l-zh/PR-1186/chapter_recurrent-modern/encoder-decoder.html

I checked warning logs for the whole book  and resolved the warning logs I found, can you review it again?

**Pull request merged**
