### PR TITLE
Chapter recurrent neural networks/text preprocessing

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-877/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Comment by mli** [comment]
Job d2l-zh/PR-877/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-877/

**Review by goldmermaid — APPROVED** [review]
Great work! @zhuyuanxiang

**Pull request merged**
