### PR TITLE
[WIP][first draft]translate installation, introduction, linear-networks, notation and preface to Chinese

### PR DESCRIPTION
**Pull request by xiaotinghe**
The following chapters have been preliminarily translated:

- Installation
- Notation
- Linear-networks

It will be further improved.

The following chapters have been simple polish based on machine translation results

- Preface
- Introduction

It looks like a short story and will take more time to translate.

### CODE REVIEW

**Comment by astonzhang** [comment]
We can leave aside the introduction chapter, which still requires major revisions

**Comment by mli** [comment]
Job d2l-zh/PR-549/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-549/

**Comment by mli** [comment]
Job d2l-zh/PR-549/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-549/

**Comment by mli** [comment]
Job d2l-zh/PR-549/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-549/

**Pull request closed without merging**
