### PR TITLE
modified:   chapter_recurrent-neural-networks/index.md

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-634/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-634/

**Comment by mli** [comment]
Job d2l-zh/PR-634/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-634/

**Comment by mli** [comment]
Job d2l-zh/PR-634/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-634/

**Comment by mli** [comment]
Job d2l-zh/PR-634/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-634/

**Comment by astonzhang** [comment]
Closing due to conflict and branch rebase. You may re-open it later on the rebased branch. Thanks.

**Pull request closed without merging**
