### PR TITLE
13.10 Transposed Convolution

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-882/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-882/

**Comment by mli** [comment]
Job d2l-zh/PR-882/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-882/

**Comment by mli** [comment]
Job d2l-zh/PR-882/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-882/

**Comment by goldmermaid** [comment]
Render checked done:
- `sec_`
- `numref`
- `cite`

forum links added

**Pull request merged**
