### PR TITLE
Fix some errors in expressions or invalid links

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-583/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by xinetzone** [comment]
modified: img/book-org.svg to Chinese

**Comment by mli** [comment]
Job d2l-zh/PR-583/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by astonzhang** [comment]
Thanks. 1. To make it easy to review, just keep one translated notebook in one PR. 2. For consistency in style, we'll use the same software to produce figures so there's no need to edit the figures.

**Comment by xinetzone** [comment]
> Thanks. 1. To make it easy to review, just keep one translated notebook in one PR. 2. For consistency in style, we'll use the same software to produce figures so there's no need to edit the figures.

**Comment by mli** [comment]
Job d2l-zh/PR-583/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by mli** [comment]
Job d2l-zh/PR-583/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-583/

**Comment by xinetzone** [comment]
There may be other changes in this chapter, so only complete these changes for now. You can close the PR.

**Pull request closed without merging**
