### PR TITLE
fix typo and translation issues in kaggle-house-price.md

### PR DESCRIPTION
**Pull request by WilliamWuLH**
fix typo and translation issues in kaggle-house-price.md

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-709/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-709/

**Comment by mli** [comment]
Job d2l-zh/PR-709/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-709/

**Comment by mli** [comment]
Job d2l-zh/PR-709/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-709/

**Review by goldmermaid — APPROVED** [review]
Thanks for your contribution! @WilliamWuLH

**Pull request merged**
