### PR TITLE
Chapter recurrent modern/machine translation and dataset

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-862/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-862/

**Comment by mli** [comment]
Job d2l-zh/PR-862/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-862/

**Comment by mli** [comment]
Job d2l-zh/PR-862/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-862/

**Comment by mli** [comment]
Job d2l-zh/PR-862/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-862/

**Comment by goldmermaid** [comment]
Fabulous work @zhuyuanxiang !

**Pull request merged**
