### PR TITLE
Chapter recurrent modern/seq2seq

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-865/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Comment by mli** [comment]
Job d2l-zh/PR-865/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Review by goldmermaid — APPROVED** [review]
Amazing work @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-865/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-865/

**Pull request merged**
