### PR TITLE
13.11 FCN

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-874/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-874/

**Comment by mli** [comment]
Job d2l-zh/PR-874/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-874/

**Comment by mli** [comment]
Job d2l-zh/PR-874/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-874/

**Comment by goldmermaid** [comment]
Render checked done:
- `sec_`
- `numref`
- `cite`

Forum links added.

**Pull request merged**
