### PR TITLE
[WIP] 13.4 anchor

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-835/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by mli** [comment]
Job d2l-zh/PR-835/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-835/

**Comment by goldmermaid** [comment]
Reviewed http://preview.d2l.ai/d2l-zh/PR-835/chapter_computer-vision/archor.html:

- no `numref` issue
- add one new citation: [Bodla et al., 2017]
- forum links updated

**Pull request merged**
