### PR TITLE
add chpter3 linear-networks of paddle

### PR DESCRIPTION
**Pull request by tngt**

### CODE REVIEW

**Comment by tngt** [comment]
Sorry, the auto-generated paddle.py caused a lot of small problems, so I submitted many changes.

**Comment by tngt** [comment]
Sorry, our auto-generated paddle.py caused a lot of small problems, so I submitted many changes. Sorry for taking up your resources.

**Comment by tngt** [comment]
@AnirudhDagar I'm  so sorry to bother you, I would like to know if this pr can be merged？

**Comment by tngt** [comment]
@AnirudhDagar I'm  so sorry to bother you, I would like to know if this pr can be merged？

**Review by AnirudhDagar — COMMENTED** [review]
Hi @tngt, I'm not sure what changes you made that caused the diffs to be so huge. We expect most changes (additions of paddle tabs) for paddle code only. From the diff, it seems the text has been changed too. Please make sure you only add the d2l paddle code tabs. Eg. `chapter_linear-networks/index.md` shows up in the diff, even though we don't need to change anything there.

Secondly, as I mentioned before d2l lib (`d2l/paddle.py`) should be autogenerated using `d2lbook build lib`. Seems like that's been an issue in this PR, since the changes should only be reflected in `d2l/paddle.py` other lib files should stay the same.

I ran `d2lbook build lib` and the diff changed. Please make sure you do the same. I'll link you to https://github.com/d2l-ai/d2l-en/blob/master/CONTRIBUTING.md again for reference of d2l development workflow to make things easier.

Feel free to ask me any questions/doubts about the same here. :))

**Comment by tngt** [comment]
> Hi @tngt, I'm not sure what changes you made that caused the diffs to be so huge. We expect most changes (additions of paddle tabs) for paddle code only. From the diff, it seems the text has been changed too. Please make sure you only add the d2l paddle code tabs. Eg. `chapter_linear-networks/index.md` shows up in the diff, even though we don't need to change anything there.
> 
> Secondly, as I mentioned before d2l lib (`d2l/paddle.py`) should be autogenerated using `d2lbook build lib`. Seems like that's been an issue in this PR, since the changes should only be reflected in `d2l/paddle.py` other lib files should stay the same.
> 
> I ran `d2lbook build lib` and the diff changed. Please make sure you do the same. I'll link you to https://github.com/d2l-ai/d2l-en/blob/master/CONTRIBUTING.md again for reference of d2l development workflow to make things easier.
> 
> Feel free to ask me any questions/doubts about the same here. :))

I'm so sorry for the trouble, I'll review what went wrong, thanks.

**Comment by tngt** [comment]
> > Hi @tngt, I'm not sure what changes you made that caused the diffs to be so huge. We expect most changes (additions of paddle tabs) for paddle code only. From the diff, it seems the text has been changed too. Please make sure you only add the d2l paddle code tabs. Eg. `chapter_linear-networks/index.md` shows up in the diff, even though we don't need to change anything there.
> > Secondly, as I mentioned before d2l lib (`d2l/paddle.py`) should be autogenerated using `d2lbook build lib`. Seems like that's been an issue in this PR, since the changes should only be reflected in `d2l/paddle.py` other lib files should stay the same.
> > I ran `d2lbook build lib` and the diff changed. Please make sure you do the same. I'll link you to https://github.com/d2l-ai/d2l-en/blob/master/CONTRIBUTING.md again for reference of d2l development workflow to make things easier.
> > Feel free to ask me any questions/doubts about the same here. :))
> 
> I'm so sorry for the trouble, I'll review what went wrong, thanks.

I want to confirm that if I should run `d2lbook build lib`  locally before pull request?

**Comment by tngt** [comment]
I describe my submission process, can you help me identify where the problem is? thank you very much
step1: I add the content of the paddle version locally;
step2: I run `d2lbook build lib` locally and generate py files for 4 frameworks (mxnet, tf, pytorch, paddle);
step3: I use git add.——>git commit -m''——>git push

**Comment by tngt** [comment]
#1132 This PR is submitted by our members, can you please evaluate whether this PR is qualified？

**Comment by AnirudhDagar** [comment]
> I want to confirm that if I should run d2lbook build lib locally before pull request?

Yes.

> I describe my submission process, can you help me identify where the problem is? thank you very much
step1: I add the content of the paddle version locally;
step2: I run d2lbook build lib locally and generate py files for 4 frameworks (mxnet, tf, pytorch, paddle);
step3: I use git add.——>git commit -m''——>git push

Yes, this sounds right. Just wanted to emphasize, that running `d2lbook build lib` should only generate paddle.py file in this case since another framework code is not touched/changed. So step 2 will modify `paddle.py` file only.

And yes in the end you can add and commit all the modified files for chapter 3.

**Comment by tngt** [comment]
> 

ok，thank you very much

**Pull request closed without merging**
