### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ShixiangWang**
阅读过程中发现几个中英文符号的使用问题。

：）

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-711/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-711/

**Comment by mli** [comment]
Job d2l-zh/PR-711/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-711/

**Comment by mli** [comment]
Job d2l-zh/PR-711/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-711/

**Comment by mli** [comment]
Job d2l-zh/PR-711/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-711/

**Review by goldmermaid — APPROVED** [review]
Thanks for being detail-oriented! @ShixiangWang

**Comment by ShixiangWang** [comment]
@goldmermaid You're welcome.

**Pull request merged**
