### PR TITLE
fix typo in chapter_introduction/index.md

### PR DESCRIPTION
**Pull request by geometryolife**
更改了一些不通顺的语句，修复了一些多余的空格，修正了一些错误术语等等。

### CODE REVIEW

**Comment by geometryolife** [comment]
> Thanks @geometryolife ! I've made some tiny comments.

That looks great, I'll add suggestions later.

**Comment by goldmermaid** [comment]
thanks for your dedication @geometryolife ! i made a few suggestion above.

**Comment by goldmermaid** [comment]
all good. merged. thanks @geometryolife !

**Comment by geometryolife** [comment]
> all good. merged. thanks @geometryolife !

My pleasure.

**Pull request merged**
