### PR TITLE
11.7 AdaGrad & 11.8 RMSProp

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-949/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-949/

**Comment by mli** [comment]
Job d2l-zh/PR-949/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-949/

**Comment by goldmermaid** [comment]
Forum links, `cite`, `numref` checked.
link render fixed.

**Comment by mli** [comment]
Job d2l-zh/PR-949/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-949/

**Pull request merged**
