### PR TITLE
Unify the function naming

### PR DESCRIPTION
**Pull request by krahets**
Unify naming of the function 'init_xavier()'.

### CODE REVIEW

**Comment by goldmermaid** [comment]
Hi @krahets ! Thanks for the hard work. Could I know where else use `init_xavier` function? We usually don't change the function names a lot, since other notebooks may call this notebook's functions.

**Comment by krahets** [comment]
Hi @goldmermaid, thanks for your reply!
I searched the keywords `xavier` and `d2l.xavier` across the whole notebook. Nowhere is this `xavier()' function used. This name change seems safe.

**Comment by goldmermaid** [comment]
Make sense to me. Could you also post a PR at [d2l-en](https://github.com/d2l-ai/d2l-en/pulls) for corresponding changes? We have 8 languages in total and every functions need to align with d2l-en. Thanks!

**Comment by krahets** [comment]
Sure. The PR at d2l-en: https://github.com/d2l-ai/d2l-en/pull/2139. Thanks!

**Pull request merged**
