### PR TITLE
chapter_recurrent-neural-networks/rnn

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-886/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Comment by mli** [comment]
Job d2l-zh/PR-886/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-886/

**Review by goldmermaid — APPROVED** [review]
Excellent! @zhuyuanxiang

**Pull request merged**
