### PR TITLE
modified:   chapter_recurrent-modern/encoder-decoder.md

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. As of now RNN, RNN-modern, and attention chap are still machine translation results. To save you time, you may wait until @xiaotinghe and @goldmermaid have the first pass on such chapters.

**Comment by mli** [comment]
Job d2l-zh/PR-636/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-636/

**Comment by mli** [comment]
Job d2l-zh/PR-636/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-636/

**Comment by mli** [comment]
Job d2l-zh/PR-636/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-636/

**Comment by mli** [comment]
Job d2l-zh/PR-636/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-636/

**Comment by mli** [comment]
Job d2l-zh/PR-636/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-636/

**Pull request merged**
