### PR TITLE
chapter_attention-mechanisms

### PR DESCRIPTION
**Pull request by xiaotinghe**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-903/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-903/

**Comment by mli** [comment]
Job d2l-zh/PR-903/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-903/

**Comment by mli** [comment]
Job d2l-zh/PR-903/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-903/

**Comment by astonzhang** [comment]
masked softmax: “含掩码的softmax”？  现在的翻译“遮蔽softmax”感觉不是很好
@xiaotinghe @goldmermaid

**Pull request merged**
