### PR TITLE
[slides] kaggle-house-price

### PR DESCRIPTION
**Pull request by goldmermaid**
Sometimes wrong with nbviewer, need to double check no "404" in
https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_multilayer-perceptrons/kaggle-house-price.ipynb  before merging.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-743/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by mli** [comment]
Job d2l-zh/PR-743/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by goldmermaid** [comment]
404 fixes (by removing space between `[**` and `**]`)

**Comment by mli** [comment]
Job d2l-zh/PR-743/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Comment by goldmermaid** [comment]
All 404 fixed! https://nbviewer.jupyter.org/format/slides/github/d2l-ai/d2l-zh-pytorch-slides/blob/main/chapter_multilayer-perceptrons/kaggle-house-price.ipynb

**Comment by mli** [comment]
Job d2l-zh/PR-743/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-743/

**Pull request merged**
