### PR TITLE
13.9 Semantic Segmentation Dataset

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-878/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-878/

**Comment by mli** [comment]
Job d2l-zh/PR-878/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-878/

**Comment by mli** [comment]
Job d2l-zh/PR-878/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-878/

**Comment by goldmermaid** [comment]
Render checked done:
- `sec_`
- 'numref`
- `cite`

**Comment by mli** [comment]
Job d2l-zh/PR-878/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-878/

**Comment by mli** [comment]
Job d2l-zh/PR-878/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-878/

**Comment by goldmermaid** [comment]
numref fixed, forum links worked

**Pull request merged**
