### PR TITLE
ch14.1-14.4

### PR DESCRIPTION
**Pull request by xiaotinghe**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-922/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-922/

**Comment by mli** [comment]
Job d2l-zh/PR-922/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-922/

**Comment by mli** [comment]
Job d2l-zh/PR-922/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-922/

**Comment by astonzhang** [comment]
Let me know when this is merged so i'll build

**Comment by mli** [comment]
Job d2l-zh/PR-922/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-922/

**Comment by mli** [comment]
Job d2l-zh/PR-922/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-922/

**Pull request merged**
