### PR TITLE
13.2 finetuning

### PR DESCRIPTION
**Pull request by goldmermaid**
Forum links done, need to check `numref` etc

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-820/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-820/

**Comment by astonzhang** [comment]
Thanks. We need to merge this asap because it's now moved one week earlier:

https://courses.d2l.ai/zh-v2/

5月30日
图像增广
微调

**Comment by astonzhang** [comment]
Besides, the forum links in 13.1, 13.2, 13.13, 13.14 in http://preview.d2l.ai/d2l-zh/PR-820/
are either pointing to English posts or Chinese posts with wrong tags (English Version not 中文版)

Can you fix everything before merging it? I'll push these four sections to release branch after that.

**Comment by goldmermaid** [comment]
> Besides, the forum links in 13.1, 13.2, 13.13, 13.14 in http://preview.d2l.ai/d2l-zh/PR-820/
> are either pointing to English posts or Chinese posts with wrong tags (English Version not 中文版)
> 
> Can you fix everything before merging it? I'll push these four sections to release branch after that.

All forum link fixed! (Thanks for pointing it out!)

**Comment by goldmermaid** [comment]
> Forum links done, need to check `numref` etc

`numref`, 'cite` check done

**Comment by mli** [comment]
Job d2l-zh/PR-820/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-820/

**Pull request merged**
