### PR TITLE
13.12 Neuralstyle

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-875/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by mli** [comment]
Job d2l-zh/PR-875/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-875/

**Comment by goldmermaid** [comment]
Render checked done:
- `sec_`
- 'numref`
- `cite`

Forum links worked

**Pull request merged**
