### PR TITLE
[MRG] Installation

### PR DESCRIPTION
**Pull request by xiaotinghe**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-560/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by mli** [comment]
Job d2l-zh/PR-560/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-560/

**Comment by astonzhang** [comment]
Closing due to conflict and branch rebase. You may re-open it later on the rebased branch. Thanks.

**Pull request closed without merging**
