### PR TITLE
[WIP] 13.7 SSD

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-849/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-849/

**Comment by mli** [comment]
Job d2l-zh/PR-849/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-849/

**Comment by mli** [comment]
Job d2l-zh/PR-849/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-849/

**Comment by mli** [comment]
Job d2l-zh/PR-849/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-849/

**Comment by goldmermaid** [comment]
- [ ] TODO: bbx didn't show in the image
image

**Comment by mli** [comment]
Job d2l-zh/PR-849/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-849/

**Comment by goldmermaid** [comment]
> 

"bbx didn't show in the image" Solved

**Comment by goldmermaid** [comment]
`numref`, `cite` check done!

**Pull request merged**
