### PR TITLE
Chapter recurrent neural networks/sequence

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-872/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Review by goldmermaid — APPROVED** [review]
Fantastic work @zhuyuanxiang

**Comment by mli** [comment]
Job d2l-zh/PR-872/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Comment by mli** [comment]
Job d2l-zh/PR-872/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-872/

**Pull request merged**
