### PR TITLE
chapter_recurrent-neural-networks/rnn-concise

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-888/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-888/

**Comment by mli** [comment]
Job d2l-zh/PR-888/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-888/

**Comment by mli** [comment]
Job d2l-zh/PR-888/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-888/

**Review by goldmermaid — APPROVED** [review]
Thanks @zhuyuanxiang !

**Comment by mli** [comment]
Job d2l-zh/PR-888/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-888/

**Pull request merged**
