### PR TITLE
[WIP] 13.5 Multisacle Object Detection

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-838/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-838/

**Comment by mli** [comment]
Job d2l-zh/PR-838/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-838/

**Comment by goldmermaid** [comment]
Reviewed http://preview.d2l.ai/d2l-zh/PR-838/chapter_computer-vision/multiscale-object-detection.html:

- no `numref` or `cite` issue
- forum links updated

**Comment by mli** [comment]
Job d2l-zh/PR-838/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-838/

**Pull request merged**
