### PR TITLE
Chapter recurrent neural networks/text preprocessing

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-782/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-782/

**Review by goldmermaid — APPROVED** [review]
Great job @zhuyuanxiang

**Comment by mli** [comment]
Job d2l-zh/PR-782/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-782/

**Comment by mli** [comment]
Job d2l-zh/PR-782/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-782/

**Pull request merged**
