### PR TITLE
Chapter optimization/optimization intro

### PR DESCRIPTION
**Pull request by zhuyuanxiang**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-780/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-780/

**Review by goldmermaid — APPROVED** [review]
Fabulous work! Thanks @zhuyuanxiang

**Comment by mli** [comment]
Job d2l-zh/PR-780/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-780/

**Comment by zhuyuanxiang** [comment]
> Fabulous work! Thanks @zhuyuanxiang

Thanks for your encouragement.

**Comment by zhuyuanxiang** [comment]
> Fabulous work! Thanks @zhuyuanxiang

Could you give me some advices for my problem that I have created many branch now and I don't know how to manage them?
Thks!

**Comment by goldmermaid** [comment]
> > Fabulous work! Thanks @zhuyuanxiang
> 
> Could you give me some advices for my problem that I have created many branch now and I don't know how to manage them?
> Thks!

Here are few cmd options:
```
## 1. Delete branch locally
## -d option stands for --delete**
git branch -d branch_name

## -D option stands for --delete --force
git branch -D branch_name

## 2. Delete branches in remote
## list remote branch (i.e. `remote_name`)
git remote -r

## delete branch in git
git push <remote_name> --delete <branch_name>
## e.g., git push origin --delete attention
```

**Comment by zhuyuanxiang** [comment]
Thanks for your help.

**Pull request merged**
