### PR TITLE
11.2 Convexity

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-915/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-915/

**Comment by mli** [comment]
Job d2l-zh/PR-915/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-915/

**Comment by mli** [comment]
Job d2l-zh/PR-915/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-915/

**Comment by goldmermaid** [comment]
Preview check done:
- cite, numref
- math
- forum links added

**Comment by mli** [comment]
Job d2l-zh/PR-915/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-915/

**Pull request merged**
