### PR TITLE
[publisher] s2.0: chapter_preliminaries/index.md

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by astonzhang** [comment]
Perhaps it's worth summarizing some patterns out of it.

**Comment by mli** [comment]
Job d2l-zh/PR-868/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-868/

**Comment by astonzhang** [comment]
@xiaotinghe  FYI, too

**Comment by goldmermaid** [comment]
General issues:
-               人称代词过多;
-               中文与英文/特殊字体之间不能加空格;
-               同样的 -> 同样地

I will summarize them to a Quip doc.

**Pull request merged**
