### PR TITLE
chapter_computer-vision/kaggle-dog.md fix translate

### PR DESCRIPTION
**Pull request by chjxz**
fix translate  chapter_computer-vision/kaggle-dog.md

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-804/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-804/

**Comment by mli** [comment]
Job d2l-zh/PR-804/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-804/

**Review by goldmermaid — APPROVED** [review]
Thanks @chjxz !

**Comment by mli** [comment]
Job d2l-zh/PR-804/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-804/

**Comment by goldmermaid** [comment]
Hi @chjxz , for your questions:
```
我发现了一些基本的排版格式，例如数字和英文，在中文中间的需要两边加上空格。**之间的是斜体。
那么**直接的空格应该怎么处理？需要在*两边都加上空格吗？
```
In this case, you need to exclude the space, and italic the two words respectively. For example, you wanna have `abc abc` to be italic, then you need to write `*abc* *abc*`.

```
**和**之间是加黑对吗？
```
Yes.

**Pull request merged**
