### PR TITLE
“参数管理”小节修改

### PR DESCRIPTION
**Pull request by liuyasilys**
修改了前两段的个别文字

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-622/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Comment by mli** [comment]
Job d2l-zh/PR-622/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-622/

**Review by goldmermaid — APPROVED** [review]

**Comment by goldmermaid** [comment]
Fantastic work! Thanks @liuyasilys

**Pull request merged**
