### PR TITLE
Update machine-translation-and-dataset.md

### PR DESCRIPTION
**Pull request by tcmyxc**
如果不加编码，win10电脑会出现 'gbk' codec can't decode byte 0x93 错误，程序无法正常运行，工具包里面的代码可以自动生成进行更新或者手动修改

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-zh/PR-930/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by goldmermaid** [comment]
Hey @tcmyxc , thanks for your contribution! Could you also make a PR at d2l-en for this code change?

**Comment by tcmyxc** [comment]
> Hey @tcmyxc , thanks for your contribution! Could you also make a PR at d2l-en for this code change?

ok

**Comment by mli** [comment]
Job d2l-zh/PR-930/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by tcmyxc** [comment]
不好意思，我对git的流程不太理解，不小心关掉了，我又重新打开了，是在是抱歉

**Comment by mli** [comment]
Job d2l-zh/PR-930/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by mli** [comment]
Job d2l-zh/PR-930/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by mli** [comment]
Job d2l-zh/PR-930/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by mli** [comment]
Job d2l-zh/PR-930/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-zh/PR-930/

**Comment by tcmyxc** [comment]
can it merge?

**Review by goldmermaid — APPROVED** [review]
Great work @tcmyxc ! Thanks

**Pull request merged**
