### PR TITLE
[Paddle]Add chapter_natural-language-processing-applications

### PR DESCRIPTION
**Pull request by tngt**

### CODE REVIEW

**Comment by w5688414** [comment]
hi, @cheungdaven  
image

it seems the error is timeout:

```
A cell timed out while it was being executed, after 1200 seconds.
```
can you adjust timeout 1200 seconds to longer, maybe 40minutes, the paddlepaddle's multigpu doesn't support jupyter notebooks, it's friendly to python scripts,  there are:

```
# 单机多卡启动，默认使用当前可见的所有卡
$ python -m paddle.distributed.launch train.py

# 单机多卡启动，设置当前使用的第0号和第1号卡
$ python -m paddle.distributed.launch --selected_gpus='0,1' train.py
```
or 
```
# 使用方式1：仅传入训练函数
# 适用场景：训练函数不需要任何参数，并且需要使用所有当前可见的GPU设备并行训练
if __name__ == '__main__':
    dist.spawn(train)

```
the docs is https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/update_cn.html#danjiduokaqidong

but the second way is multiprocessing, it seems that the jupyter doesn't work well on a multiprocessing way, I got some errors on my local machine

**Comment by cheungdaven** [comment]
Hi @w5688414. To ensure the notebook be user-friendly and easy to compile, we cannot extend the timeout limit.  Maybe you can try different solutions ? (like reduce the training iterations, we a lower accuracy is expected.)

**Comment by cheungdaven** [comment]
@d2l-bot please rebuild

**Comment by tngt** [comment]
@cheungdaven hello， could you review it again? thanks!!!

**Comment by cheungdaven** [comment]
LGTM @tngt @w5688414 , thank you for the contribution.

**Pull request merged**
